version: 0.2
phases:
  install:
    commands:
      - echo "Installing HTML validator..."
      - npm install -g htmlhint
  build:
    commands:
      - echo "Running HTML Validation on index.html..."
      - htmlhint index.html
artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/**/*
