version: 0.2
phases:
  install:
    commands:
      - echo "Installing HTML validator..."
      - npm install -g htmlhint
  build:
    commands:
      - echo "Running HTML Validation on index.html..."
      - htmlhint index.html
      - chmod +x cleanup.sh
      - chmod +x reload_nginx.sh
artifacts:
  files:
    - index.html
    - appspec.yml
    - cleanup.sh
    - reload_nginx.sh
